# Generated by Django 2.1.3 on 2019-02-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('beer_id', models.AutoField(primary_key=True, serialize=False)),
                ('beer_name', models.CharField(blank=True, max_length=45, null=True)),
                ('candidate', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'rating_beer',
            },
        ),
        migrations.CreateModel(
            name='RatingBeer',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=50, null=True)),
                ('beer_id', models.IntegerField(blank=True, null=True)),
                ('foreign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Beer')),
            ],
            options={
                'db_table': 'rating_ratingbeer',
            },
        ),
    ]
