# Generated by Django 2.1.3 on 2019-02-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBeer',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=50, null=True)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Beer')),
            ],
        ),
    ]
