# Generated by Django 2.1.3 on 2019-02-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_ratebeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
