# Generated by Django 2.1.3 on 2019-02-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_beer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
