# Generated by Django 2.1.3 on 2019-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20190218_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
