# Generated by Django 2.1.3 on 2019-02-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20190218_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingbeer',
            name='foreign_id',
        ),
    ]
