# Generated by Django 2.1.3 on 2019-02-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_remove_ratingbeer_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingbeer',
            name='tap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
