# Generated by Django 2.1.3 on 2019-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_ratingbeer_tap'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.CharField(blank=True, db_column='ABV', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='country_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='style_big',
            field=models.CharField(blank=True, db_column='Style_big', max_length=45, null=True),
        ),
    ]
